apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: net
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nginx
                port:
                  name: nginx-https
  tls:
    - hosts:
      - localhost
      secretName: nginx-tls