apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: net
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    nodePort: 30000
  - name: multitool
    port: 8080
    nodePort: 30001  
  selector:
    app: multitool
  type: NodePort
 