apiVersion: v1
kind: Service
metadata:
  name: back
  namespace: app
spec:
  ports:
  - name: back
    port: 80
    protocol: TCP
    targetPort: 80 
  selector:
    app: back
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: app
spec:
  ports:
  - name: front
    port: 80
    protocol: TCP
    targetPort: 80 
  selector:
    app: front
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: app
spec:
  ports:
  - name: cache
    port: 80
    protocol: TCP
    targetPort: 80 
  selector:
    app: cache
 
 