apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.prometheus }}
      targetPort: {{ .Values.ports.prometheus }}
      protocol: TCP
      name: prometheus
  selector:
    app: {{ .Values.label }}

